name: CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
jobs:

  docker-build:
    name: Docker Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0 # fetch all history for all branches and tags
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: "GITHUB_ACTION_${{ github.run_number }}"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: mmore500/docker-texlive-full
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
